config/routes.rb
Rails.application.routes.draw do
  root 'group_events#index'

  resources :drafts, except: :index do
    member do
      post :publish
    end
  end

  resources :published_events, only: [ :edit, :update, :destroy ]
  resources :group_events, only: :index

  namespace :api do
    namespace :v1 do
      resources :drafts, only: [ :create, :update, :destroy ] do
        member do
          post :publish
        end
      end

      resources :published_events, only: [ :update, :destroy ]
      resources :group_events, only: :index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group_event.rb
class GroupEvent < ApplicationRecord
  extend Enumerize
  DURATIONS = [30, 60]

  enumerize :event_type, in: %i(draft published),
    default: :draft,
    scope: true,
    predicates: true

  scope :not_deleted, -> { where(deleted: false) }
  scope :published, -> { not_deleted.with_event_type(:published) }
  scope :draft, -> { not_deleted.with_event_type(:draft) }

  def mark_as_deleted
    update_attributes(deleted: true)
  end

  def publish
    update_attributes(event_type: self.class.event_type.published)
  end
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    def not_found
      respond_with_errors(['Not found'], :not_found)
    end

    def respond_with_errors(errors, status = :unprocessable_entity)
      render json: { errors: errors }, status: status
    end
  end
end

app/controllers/api/v1/drafts_controller.rb
module Api
  module V1
    class DraftsController < Api::ApplicationController
      def create
        form = Drafts::Form.new
        form.attributes = permitted_params(form)

        if form.valid? && draft = repository.create(form.attributes)
          render_draft(draft)
        else
          respond_with_errors(form.errors)
        end
      end

      def update
        draft = repository.find(params[:id])
        form = Drafts::Form.new(draft.attributes)
        form.attributes = permitted_params(form)

        if form.valid? && draft.update_attributes(form.attributes)
          render_draft(draft)
        else
          respond_with_errors(form.errors)
        end
      end

      def destroy
        draft = repository.find(params[:id])
        if draft.mark_as_deleted
          head :no_content
        else
          respond_with_errors([ I18n.t('group_event.failed_delete') ])
        end
      end

      def publish
        draft = GroupEvent.find(params[:id])
        if draft.published?
          respond_with_errors(base: [ I18n.t('group_event.already_published') ])
        else
          form = PublishedEvents::Form.new(draft.attributes)
          if form.valid? && draft.publish
            render_draft(draft)
          else
            respond_with_errors(base: [ I18n.t('group_event.failed_publish') ])
          end
        end
      end

      private

      def repository
        GroupEvent.draft
      end

      def render_draft(draft)
        render json: GroupEventSerializer.new(draft)
      end

      def permitted_params(form)
        params.require(:draft).permit(form.form_attributes).to_h
      end
    end
  end
end

app/controllers/api/v1/group_events_controller.rb
module Api
  module V1
    class GroupEventsController < ApplicationController
      def index
        render json: { group_events: GroupEventSerializer.map(GroupEvent.all) }
      end
    end
  end
end

app/controllers/api/v1/published_events_controller.rb
module Api
  module V1
    class PublishedEventsController < Api::ApplicationController
      def update
        published_event = repository.find(params[:id])
        form = PublishedEvents::Form.new(published_event.attributes)
        form.attributes = permitted_params(form)

        if form.valid? && published_event.update_attributes(form.attributes)
          render_published_event(published_event)
        else
          respond_with_errors(base: [ I18n.t('group_event.failed_update') ])
        end
      end

      def destroy
        published_event = repository.find(params[:id])
        if published_event.mark_as_deleted
          head :no_content
        else
          respond_with_errors(base: [ I18n.t('group_event.failed_delete') ])
        end
      end

      private

      def repository
        GroupEvent.published
      end

      def render_published_event(published_event)
        render json: GroupEventSerializer.new(published_event)
      end

      def permitted_params(form)
        params.require(:published_event).permit(form.form_attributes).to_h
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  def new
    @form = Drafts::Form.new
  end

  def create
    @form = Drafts::Form.new
    @form.attributes = permitted_params(@form)

    if @form.valid? && repository.create(@form.attributes)
      redirect_to root_path, notice: t('group_event.successfully_created')
    else
      flash.now[:error] = t('group_event.failed_creation')
      render :new
    end
  end

  def edit
    @draft = repository.find(params[:id])
    @form = Drafts::Form.new(@draft.attributes)
  end

  def update
    @draft = repository.find(params[:id])
    @form = Drafts::Form.new(@draft.attributes)
    @form.attributes = permitted_params(@form)

    if @form.valid? && @draft.update_attributes(@form.attributes)
      redirect_to root_path, notice: t('group_event.successfully_updated')
    else
      flash.now[:error] = t('group_event.failed_update')
      render :edit
    end
  end

  def destroy
    @draft = repository.find(params[:id])
    if @draft.mark_as_deleted
      redirect_to root_path, notice: t('group_event.successfully_deleted')
    else
      redirect_to root_path, flash: { error: t('group_event.failed_delete') }
    end
  end

  def publish
    @draft = GroupEvent.find(params[:id])
    if @draft.published?
      redirect_to root_path, flash: { error: t('group_event.already_published') }
    else
      @form = PublishedEvents::Form.new(@draft.attributes)
      if @form.valid? && @draft.publish
        redirect_to root_path, notice: t('group_event.successfully_published')
      else
        flash.now[:error] = t('group_event.failed_publish')
        render :edit
      end
    end
  end

  private

  def repository
    GroupEvent.draft
  end

  def permitted_params(form)
    params.require(:draft).permit(form.form_attributes).to_h
  end
end

app/controllers/group_events_controller.rb
class GroupEventsController < ApplicationController
  def index
    @published_events = GroupEventPresenter.map(GroupEvent.published)
    @drafts = GroupEventPresenter.map(GroupEvent.draft)
  end
end

app/controllers/published_events_controller.rb
class PublishedEventsController < ApplicationController
  def edit
    @published_event = repository.find(params[:id])
    @form = PublishedEvents::Form.new(@published_event.attributes)
  end

  def update
    @published_event = repository.find(params[:id])
    @form = PublishedEvents::Form.new(@published_event.attributes)
    @form.attributes = permitted_params(@form)

    if @form.valid? && @published_event.update_attributes(@form.attributes)
      redirect_to root_path, notice: t('group_event.successfully_updated')
    else
      flash.now[:error] = t('group_event.failed_update')
      render :edit
    end
  end

  def destroy
    @published_event = repository.find(params[:id])
    if @published_event.mark_as_deleted
      redirect_to root_path, notice: t('group_event.successfully_deleted')
    else
      redirect_to root_path, flash: { error: t('group_event.failed_delete') }
    end
  end

  private

  def repository
    GroupEvent.published
  end

  def permitted_params(form)
    params.require(:published_event).permit(form.form_attributes).to_h
  end
end

app/helpers/application_helper.rb
# https://gist.github.com/suryart/7418454
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info'}[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: 'close', data: {dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/views/drafts/_form.html.slim
.form-group
  = f.label :title, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :title, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :location, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :location, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :starts_at, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :starts_at, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :duration, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :duration, as: :select, collection: form.duration_collection, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :description, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :description, as: :text, label: false, input_html: {class: 'form-control'}

.form-group
  .actions.col-sm-offset-2.col-sm-10
    = f.button :submit, t('actions.save'), class: 'btn btn-primary'

app/views/drafts/edit.html.slim
.container.content-bottom
  h4
    = "#{ t('actions.edit') } #{ t('activerecord.models.draft') }"
  br
  = simple_form_for @form, as: :draft, url: draft_path(@draft), method: :put, html: { class: 'form-horizontal' } do |f|
    = render 'drafts/form', form: @form, f: f

app/views/drafts/new.html.slim
.container.content-bottom
  h4
    = "#{ t('actions.new') } #{ t('activerecord.models.draft') }"
  br
  = simple_form_for @form, as: :draft, url: drafts_path, method: :post, html: { class: 'form-horizontal' } do |f|
    = render 'drafts/form', form: @form, f: f

app/views/group_events/index.html.slim
= link_to new_draft_path, class: 'btn btn-primary btn-ge' do
  span.btn-ge__icon.icon.glyphicon.glyphicon-plus
  = t('actions.add')

br
br

- if @published_events.empty? && @drafts.empty?
  h3
    = t('group_event.not_exists')
- else
  table.table.table-bordered
    thead
      th = t('activerecord.attributes.group_event_attributes.title')
      th = t('activerecord.attributes.group_event_attributes.event_type')
      th = t('group_event.ends_at')
      th = t('activerecord.attributes.group_event_attributes.location')
      th = t('activerecord.attributes.group_event_attributes.description')
      th = t('actions.label')
    tbody
      - @drafts.each do |presenter|
        tr
          td
            = link_to presenter.title, edit_draft_path(presenter.subject)
          td
            span.label.label-primary
              = presenter.label
          td
            = presenter.ends_at
          td
            = presenter.location
          td
            = presenter.description
          td
            = link_to publish_draft_path(presenter.subject), method: :post, class: 'btn btn-sm btn-success btn-ge' do
              span.btn-ge__icon.icon.glyphicon.glyphicon-eye-open
              = t('actions.publish')
            = link_to draft_path(presenter), method: :delete, class: 'btn btn-sm btn-danger btn-ge btn-ge--right',
                data: { confirm: t('actions.confirmation') } do
              span.btn-ge__icon.icon.glyphicon.glyphicon-trash
              = t('actions.delete')

      - @published_events.each do |presenter|
        tr
          td
            = link_to presenter.title, edit_published_event_path(presenter.subject)
          td
            span.label.label-primary
              = presenter.label
          td
            = presenter.ends_at
          td
            = presenter.location
          td
            = presenter.description
          td
            = link_to published_event_path(presenter.subject), method: :delete,
                class: 'btn btn-sm btn-danger btn-ge', data: { confirm: t('actions.confirmation') } do
              span.btn-ge__icon.icon.glyphicon.glyphicon-trash
              = t('actions.delete')

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t('label')
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    nav.navbar.navbar-default
      .container.container-fluid
        .navbar-header
          button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          = link_to t('label'), root_path, class: 'navbar-brand'
    .container
      = flash_messages
      = yield

app/views/published_events/_form.html.slim
.form-group
  = f.label :title, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :title, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :location, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :location, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :starts_at, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :starts_at, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :duration, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :duration, as: :select, collection: form.duration_collection, label: false, input_html: {class: 'form-control'}
.form-group
  = f.label :description, class: 'col-sm-2 control-label'
  .col-sm-5
    = f.input :description, as: :text, label: false, input_html: {class: 'form-control'}

.form-group
  .actions.col-sm-offset-2.col-sm-10
    = f.button :submit, t('actions.save'), class: 'btn btn-primary'

app/views/published_events/edit.html.slim
.container.content-bottom
  h4
    = "#{ t('actions.edit') } #{ t('activerecord.models.published_event') }"
  br
  = simple_form_for @form, as: :published_event, url: published_event_path(@published_event), method: :put, html: { class: 'form-horizontal' } do |f|
    = render 'published_events/form', form: @form, f: f